import type { MarketCategory } from "@shared/schema";

export interface SeedMarket {
  question: string;
  description: string;
  rules: string;
  category: MarketCategory;
  emoji: string;
  liquidity: number;
  /** outcome names; two entries Yes/No make a binary market */
  outcomes?: string[];
  startProbabilities: number[];
  currentProbabilities: number[];
  ageDays: number;
  daysLeft: number;
  featured?: boolean;
  comments?: string[];
}

const yn = (p: number) => [p, 1 - p];

export const seedMarkets: SeedMarket[] = [
  {
    question: "Will Bitcoin close above $150,000 on December 31, 2026?",
    description:
      "This market resolves to Yes if the BTC/USD daily close on Coinbase for December 31, 2026 (UTC) is strictly above $150,000.",
    rules:
      "The resolution source is the Coinbase BTC-USD daily candle close at 23:59:59 UTC on December 31, 2026. If Coinbase data is unavailable, the CoinGecko aggregate close will be used. Any price exactly at $150,000.00 resolves No.",
    category: "Crypto",
    emoji: "₿",
    liquidity: 4000,
    startProbabilities: yn(0.35),
    currentProbabilities: yn(0.41),
    ageDays: 35,
    daysLeft: 118,
    featured: true,
    comments: [
      "ETF inflows have been insane this quarter. 41% feels low.",
      "Halving cycle says the peak was already in. Fading this.",
      "Anyone else watching the miner capitulation data? Bullish divergence.",
    ],
  },
  {
    question: "Fed decision in September?",
    description:
      "What will the Federal Open Market Committee decide about the federal funds target range at its September 2026 meeting?",
    rules:
      "Resolves according to the official FOMC statement published on federalreserve.gov after the September 2026 meeting. '50+ bps decrease' includes any cut of 50 basis points or more. If no meeting takes place the market resolves 'No change'.",
    category: "Business",
    emoji: "🏦",
    liquidity: 5000,
    outcomes: ["25 bps decrease", "50+ bps decrease", "No change", "Increase"],
    startProbabilities: [0.45, 0.1, 0.4, 0.05],
    currentProbabilities: [0.62, 0.14, 0.22, 0.02],
    ageDays: 28,
    daysLeft: 13,
    featured: true,
    comments: ["Dot plot basically confirmed 25.", "Labor data was soft again, 50 is live."],
  },
  {
    question: "2026-27 UEFA Champions League winner?",
    description: "Which club will lift the 2026-27 UEFA Champions League trophy?",
    rules:
      "Resolves to the club that wins the 2026-27 UEFA Champions League final according to UEFA. A win on penalties counts. 'Other' covers any club not listed.",
    category: "Sports",
    emoji: "⚽",
    liquidity: 3500,
    outcomes: ["Real Madrid", "Man City", "Bayern", "PSG", "Barcelona", "Liverpool", "Other"],
    startProbabilities: [0.18, 0.17, 0.12, 0.13, 0.11, 0.1, 0.19],
    currentProbabilities: [0.16, 0.15, 0.11, 0.17, 0.13, 0.09, 0.19],
    ageDays: 20,
    daysLeft: 270,
    featured: true,
    comments: ["PSG squad looks scary this year.", "Never bet against Madrid in Europe."],
  },
  {
    question: "Will OpenAI release GPT-6 before the end of 2026?",
    description:
      "Resolves Yes if OpenAI makes a model officially named 'GPT-6' generally available (API or ChatGPT) to the public before January 1, 2027.",
    rules:
      "A research preview or limited waitlist does not count. The model must be available to paying customers without an invite. Naming must include 'GPT-6' (GPT-6 mini, GPT-6 Turbo etc. count).",
    category: "Tech",
    emoji: "🤖",
    liquidity: 3000,
    startProbabilities: yn(0.5),
    currentProbabilities: yn(0.33),
    ageDays: 45,
    daysLeft: 118,
    comments: ["They said 'this year' at dev day but they always slip.", "NO. Compute is the bottleneck."],
  },
  {
    question: "Will Starship complete an orbital flight with booster catch in 2026?",
    description:
      "Resolves Yes if a Starship launch in 2026 reaches orbit (or a planned trans-atmospheric trajectory) AND the Super Heavy booster is caught by the launch tower arms on the same flight.",
    rules: "Both conditions must occur on the same flight. Resolution based on SpaceX official statements and livestream footage.",
    category: "Science",
    emoji: "🚀",
    liquidity: 2500,
    startProbabilities: yn(0.55),
    currentProbabilities: yn(0.68),
    ageDays: 60,
    daysLeft: 118,
    comments: ["Already did the catch, orbit is the easy part now."],
  },
  {
    question: "Will Taylor Swift announce a new studio album before 2027?",
    description: "Resolves Yes if Taylor Swift officially announces a new original studio album (not a re-recording) before January 1, 2027.",
    rules: "Announcement must come from Taylor Swift or her label via official channels. Taylor's Version re-records do not count.",
    category: "Culture",
    emoji: "🎤",
    liquidity: 1500,
    startProbabilities: yn(0.4),
    currentProbabilities: yn(0.57),
    ageDays: 15,
    daysLeft: 118,
  },
  {
    question: "Will Ethereum ETF staking be approved by the SEC before September 2026?",
    description: "Resolves Yes if the SEC approves any spot Ethereum ETF that includes staking of the underlying ETH before September 1, 2026.",
    rules: "Resolution based on SEC filings and official approval orders.",
    category: "Crypto",
    emoji: "Ξ",
    liquidity: 2000,
    startProbabilities: yn(0.3),
    currentProbabilities: yn(0.92),
    ageDays: 90,
    daysLeft: -2,
    comments: ["Called it.", "Resolved Yes, easiest money of the year."],
  },
  {
    question: "Will the US unemployment rate exceed 5% in any month of 2026?",
    description: "Resolves Yes if the BLS reports a seasonally adjusted U-3 unemployment rate above 5.0% for any month of 2026.",
    rules: "Resolution based on the initial BLS Employment Situation release for each month. Revisions are ignored.",
    category: "Business",
    emoji: "📉",
    liquidity: 2500,
    startProbabilities: yn(0.25),
    currentProbabilities: yn(0.29),
    ageDays: 50,
    daysLeft: 150,
  },
  {
    question: "Will Apple ship a foldable iPhone in 2026?",
    description: "Resolves Yes if Apple begins retail sales of an iPhone with a foldable display before January 1, 2027.",
    rules: "Pre-orders do not count. Devices must be delivered to customers. Announcement alone is not sufficient.",
    category: "Tech",
    emoji: "📱",
    liquidity: 2000,
    startProbabilities: yn(0.45),
    currentProbabilities: yn(0.38),
    ageDays: 30,
    daysLeft: 118,
    comments: ["Supply chain leaks point to 2027.", "September event will settle this."],
  },
  {
    question: "2026 FIFA World Cup winner?",
    description: "Which national team will win the 2026 FIFA World Cup?",
    rules: "Resolves to the team that wins the final according to FIFA. Penalties count. 'Other' covers any team not listed.",
    category: "Sports",
    emoji: "🏆",
    liquidity: 4000,
    outcomes: ["Spain", "France", "Argentina", "Brazil", "England", "Germany", "Other"],
    startProbabilities: [0.13, 0.15, 0.14, 0.12, 0.13, 0.09, 0.24],
    currentProbabilities: [0.15, 0.16, 0.12, 0.11, 0.14, 0.08, 0.24],
    ageDays: 70,
    daysLeft: 300,
    featured: true,
    comments: ["Spain's midfield is unreal.", "Argentina without Messi at full strength... hmm."],
  },
  {
    question: "Will a US state ban smartphones in all K-12 schools in 2026?",
    description: "Resolves Yes if any US state enacts a statewide law requiring bell-to-bell smartphone bans across all public K-12 schools during 2026.",
    rules: "Must be signed into law during calendar 2026. Policies limited to instructional time only do not count.",
    category: "Politics",
    emoji: "🏛️",
    liquidity: 1500,
    startProbabilities: yn(0.5),
    currentProbabilities: yn(0.61),
    ageDays: 22,
    daysLeft: 118,
  },
  {
    question: "Will Artemis III land humans on the Moon before 2028?",
    description: "Resolves Yes if NASA's Artemis III mission lands astronauts on the lunar surface before January 1, 2028.",
    rules: "Based on NASA official confirmation of a crewed lunar landing under the Artemis III designation.",
    category: "Science",
    emoji: "🌕",
    liquidity: 2500,
    startProbabilities: yn(0.3),
    currentProbabilities: yn(0.22),
    ageDays: 80,
    daysLeft: 480,
    comments: ["Lander delays keep piling up. Under 20% by Christmas."],
  },
  {
    question: "Which chain will have the highest DEX volume in December 2026?",
    description: "Which blockchain will record the highest total DEX volume for the month of December 2026, per DefiLlama?",
    rules: "DefiLlama chain DEX volume dashboards are the resolution source. L2s are counted separately from Ethereum mainnet.",
    category: "Crypto",
    emoji: "◎",
    liquidity: 2500,
    outcomes: ["Ethereum", "Solana", "Base", "BNB Chain", "Other"],
    startProbabilities: [0.4, 0.3, 0.15, 0.1, 0.05],
    currentProbabilities: [0.35, 0.36, 0.17, 0.08, 0.04],
    ageDays: 25,
    daysLeft: 118,
  },
  {
    question: "Will GTA VI sell more than 30 million copies in its first month?",
    description: "Resolves Yes if Take-Two Interactive reports or credible sales trackers confirm 30M+ units sold within 30 days of release.",
    rules: "Resolution based on Take-Two investor communications or Circana/GfK data. If release slips beyond 2026 the market resolves No.",
    category: "Culture",
    emoji: "🎮",
    liquidity: 2000,
    startProbabilities: yn(0.5),
    currentProbabilities: yn(0.64),
    ageDays: 40,
    daysLeft: 118,
    comments: ["RDR2 did 17M in 8 days. 30M in a month is very doable."],
  },
  {
    question: "Will Nvidia's market cap exceed $6 trillion at any close in 2026?",
    description: "Resolves Yes if NVDA's market capitalization at any regular-session close in 2026 exceeds $6,000,000,000,000.",
    rules: "Market cap computed as closing price × shares outstanding per Nasdaq. Intraday highs do not count.",
    category: "Business",
    emoji: "💹",
    liquidity: 3500,
    startProbabilities: yn(0.45),
    currentProbabilities: yn(0.52),
    ageDays: 33,
    daysLeft: 118,
    featured: true,
  },
  {
    question: "Who will win the 2026 US midterms House majority?",
    description: "Which party will hold the majority in the US House of Representatives after the November 2026 midterm elections?",
    rules: "Resolves according to the party with the most seats when the 120th Congress is sworn in, per the House Clerk.",
    category: "Politics",
    emoji: "🗳️",
    liquidity: 5000,
    outcomes: ["Democrats", "Republicans"],
    startProbabilities: [0.5, 0.5],
    currentProbabilities: [0.58, 0.42],
    ageDays: 100,
    daysLeft: 60,
    featured: true,
    comments: ["Generic ballot is D+3 right now.", "Redistricting in Texas changes the math."],
  },
  {
    question: "Will a major AI lab release a 10M+ token context model in 2026?",
    description:
      "Resolves Yes if OpenAI, Anthropic, Google DeepMind, Meta or xAI make a model with a documented 10,000,000+ token context window available via public API in 2026.",
    rules: "Must be documented in official API docs and callable by any paying developer. Research demos do not count.",
    category: "Tech",
    emoji: "🧠",
    liquidity: 1500,
    startProbabilities: yn(0.35),
    currentProbabilities: yn(0.44),
    ageDays: 18,
    daysLeft: 118,
  },
  {
    question: "Will there be a ceasefire in Ukraine before 2027?",
    description: "Resolves Yes if Russia and Ukraine both officially announce a general ceasefire that holds for at least 30 consecutive days before January 1, 2027.",
    rules: "Requires public confirmation from both governments. Localized or humanitarian pauses do not count.",
    category: "World",
    emoji: "🕊️",
    liquidity: 3000,
    startProbabilities: yn(0.3),
    currentProbabilities: yn(0.27),
    ageDays: 55,
    daysLeft: 118,
  },
];
